training:
  wd: 0.0001
  lr: 0.0001
  log_jaccard: false
model:
  decoder_normalization: IN
  n_outputs: 1
  spatial_dropout: 0.1
  backbone: resnet50
  decoder: FPN
data_sampling:
  train:
    data_provider:
      bfpn_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
  eval:
    data_provider:
      bfpn_val:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"